name: render page
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # every week on Sunday
    - cron: "0 0 * * 0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.10
      - run: |
          pip install -r requirements.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mike deploy --push --update-aliases latest
          mike set-default latest --push